import { VideoItem } from "@/types/youtube";

export const sampleVideos: VideoItem[] = [
  {
    id: "dQw4w9WgXcQ",
    title: "Rick Astley - Never Gonna Give You Up (Official Video)",
    thumbnail: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    channelTitle: "Rick Astley",
    publishedAt: "2009-10-25T06:57:33Z",
    duration: "PT3M33S",
    description:
      "The official video for 'Never Gonna Give You Up' by Rick Astley",
  },
  {
    id: "9bZkp7q19f0",
    title: "PSY - GANGNAM STYLE (강남스타일) M/V",
    thumbnail: "https://i.ytimg.com/vi/9bZkp7q19f0/hqdefault.jpg",
    channelTitle: "officialpsy",
    publishedAt: "2012-07-15T08:34:21Z",
    duration: "PT4M13S",
    description: "PSY - GANGNAM STYLE (강남스타일) M/V",
  },
  {
    id: "kJQP7kiw5Fk",
    title: "Luis Fonsi - Despacito ft. Daddy Yankee",
    thumbnail: "https://i.ytimg.com/vi/kJQP7kiw5Fk/hqdefault.jpg",
    channelTitle: "LuisFonsiVEVO",
    publishedAt: "2017-01-12T16:00:14Z",
    duration: "PT4M42S",
    description: "Despacito - Luis Fonsi ft. Daddy Yankee",
  },
  {
    id: "JGwWNGJdvx8",
    title: "Ed Sheeran - Shape of You (Official Video)",
    thumbnail: "https://i.ytimg.com/vi/JGwWNGJdvx8/hqdefault.jpg",
    channelTitle: "Ed Sheeran",
    publishedAt: "2017-01-30T10:00:07Z",
    duration: "PT3M54S",
    description: "Ed Sheeran - Shape of You (Official Video)",
  },
  {
    id: "fJ9rUzIMcZQ",
    title: "Queen - Bohemian Rhapsody (Official Video)",
    thumbnail: "https://i.ytimg.com/vi/fJ9rUzIMcZQ/hqdefault.jpg",
    channelTitle: "Queen",
    publishedAt: "2008-08-01T14:09:03Z",
    duration: "PT5M55S",
    description: "Queen - Bohemian Rhapsody (Official Video)",
  },
  {
    id: "hT_nvWreIhg",
    title: "The Weeknd - Blinding Lights (Official Video)",
    thumbnail: "https://i.ytimg.com/vi/hT_nvWreIhg/hqdefault.jpg",
    channelTitle: "The Weeknd",
    publishedAt: "2020-01-14T22:00:12Z",
    duration: "PT4M20S",
    description: "The Weeknd - Blinding Lights (Official Video)",
  },
  {
    id: "YQHsXMglC9A",
    title: "Adele - Hello (Official Music Video)",
    thumbnail: "https://i.ytimg.com/vi/YQHsXMglC9A/hqdefault.jpg",
    channelTitle: "Adele",
    publishedAt: "2015-10-22T13:06:32Z",
    duration: "PT6M7S",
    description: "Adele - Hello (Official Music Video)",
  },
  {
    id: "OPf0YbXqDm0",
    title: "Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars",
    thumbnail: "https://i.ytimg.com/vi/OPf0YbXqDm0/hqdefault.jpg",
    channelTitle: "Mark Ronson",
    publishedAt: "2014-11-19T16:00:06Z",
    duration: "PT4M30S",
    description: "Mark Ronson - Uptown Funk (Official Video) ft. Bruno Mars",
  },
  {
    id: "TUVcZfQe-Kw",
    title: "Lorde - Royals (Official Video)",
    thumbnail: "https://i.ytimg.com/vi/TUVcZfQe-Kw/hqdefault.jpg",
    channelTitle: "Lorde",
    publishedAt: "2013-06-03T05:00:37Z",
    duration: "PT3M10S",
    description: "Lorde - Royals (Official Video)",
  },
  {
    id: "L_jWHffIx5E",
    title: "Smash Mouth - All Star (Official Music Video)",
    thumbnail: "https://i.ytimg.com/vi/L_jWHffIx5E/hqdefault.jpg",
    channelTitle: "Smash Mouth",
    publishedAt: "2010-12-07T22:30:01Z",
    duration: "PT3M20S",
    description: "Smash Mouth - All Star (Official Music Video)",
  },
];
